### ISSUE TITLE
grid.locale-sq.js overrides localization for English

### ISSUE THREAD

**Issue by jimitndiaye** [tonytomov/jqGrid#882] opened 2017-09-06 11:40 UTC
```
$.jgrid.regional["en"] = {
	defaults : {
		recordtext: "Shfaq {0} - {1}/{2}",
		emptyrecords: "Nuk ka rreshta për të shfaqur",
		loadtext: "Duke u ngarkuar...",
...
```
As you can see it uses ```en``` as its language key, overriding the default English translations. As a result the translations get overridden.

**Comment by tonytomov** [comment] 2017-09-06 15:56
Hello,

I'm not sure what is the problem. If you overwrite any language translations into lang file they will be used into the grid. For me it is not a problem. Sorry to say this, but I'm unable to understand the problem.

**Comment by jimitndiaye** [comment] 2017-09-06 16:08
If you check all the other language files they have something similar to:
```$.jgrid.regional["<lang>"]``` where ```lang``` is their corresponding language code (and thus unique). This file instead of using ```sq``` uses ```en``` so it overrides the original English translation (which, correctly, uses ```en```).

Due to this when you use ```$.jgrid.setRegional(gridId, { regional: "en" })```, instead of getting English you get that Albanian.

This file should be fixed to say ```$.jgrid.regional["sq"] = { ...```

**Comment by tonytomov** [comment] 2017-09-06 16:22
If you do 

```js
$.jgrid.regional["en"] = {
	defaults : {
		recordtext: "Shfaq {0} - {1}/{2}",
...
```

you overwrite the texts in the language en file.

it is the same if you have initially set

var somevaraible['en'] = 1;


and then after set this you do

somevaraible['en'] = 2;

of course after calling 

console.log(somevaraible['en'])

it will give you 2.

What you do is equivalent to set these texts after the lang file.

With other words it can be dynamically changed.

**Comment by jimitndiaye** [comment] 2017-09-06 16:26
It is literally two letters that are incorrect as compared to **every** other language file. It is a bug. Your own demo app which I linked above shows you the bug. Quite frankly closing the issue without attempting to understand a legitimate bug seriously dampens our resolve to obtain a commercial license for this product if this is the kind of support we can expect.

**Comment by tonytomov** [comment] 2017-09-06 16:34
Sorry to close the issue, but you have added(updated)  the demo and description of this after my comment. It is better always to provide a demo which demonstrates the problem.  

When a bug is reported it should be pointed with proofs as you do after closing.

Will check this and replay ASAP.

**Comment by tonytomov** [comment] 2017-09-06 16:43
I have see the problem. It is fixed https://github.com/tonytomov/jqGrid/commit/b09edc866ce288e9a886f7f111aa1c6f713c2e4a . Sorry that I do not understand it.
Kind Regards

**Comment by jimitndiaye** [comment] 2017-09-06 16:45
Thanks









On Wed, Sep 6, 2017 at 5:43 PM +0100, "Tony Tomov" <notifications@github.com> wrote:












I have see the problem. It is fixed b09edc8 . Sorry that I do not understand it.

Kind Regards

**Closed** 2017-09-06 17:05 UTC
Labels: Bug

**Comment by tonytomov** [comment] 2017-09-11 08:22
Hello,

If the problem is fixed, could you please close the issue.

Thank you.

**Comment by jimitndiaye** [comment] 2017-09-11 09:06
It seems to already be closed
