### ISSUE TITLE
OnSelectCell triggers even when the cell is not editable

### ISSUE THREAD

**Issue by guylhermetabosa** [tonytomov/jqGrid#855] opened 2017-04-27 17:38 UTC
Hello,

Looking at the docs, http://www.guriddo.net/documentation/guriddo/javascript/user-guide/editing/) says that: The event OnSelectCell only applies to cells that are not editable and fires after the cell is selected. However it fires even when the cell is editable, is this a bug? Is there any demo of this feature working, I'd like to know if a missing something. I'll provide a fiddle for that.

https://jsfiddle.net/uedur83v/

**Comment by tonytomov** [comment] 2017-04-28 06:52
Hello,

Thank you for finding this problem. We have fixed it: https://github.com/tonytomov/jqGrid/commit/a1ec13d5b935b63c5ae3ac6616e1de6aaaada05e

Please let me know if the problem is fixed.

Thank you

Kind Regards,
Tony

**Comment by guylhermetabosa** [comment] 2017-04-28 13:33
I'll test as soon as possible, but looking to the source should work.

Thanks for the fix so quickly.

Kind regards,
Guylherme

**Comment by tonytomov** [comment] 2017-08-14 14:17
I close the issue. If there is a problem, please reopen it.
Thank you.

**Closed by tonytomov** 2017-08-14 14:17 UTC
Labels: Bug
