### ISSUE TITLE
Does your code handles jquery 3?

### ISSUE THREAD

**Issue by Koi7** [tonytomov/jqGrid#939] opened 2019-02-05 10:16 UTC
This [jquery 3 breaking change](https://jquery.com/upgrade-guide/3.0/#breaking-change-select-multiple-with-nothing-selected-returns-an-empty-array) seems to be still  unhandled.

**Comment by Koi7** [comment] 2019-02-05 13:49
Check triggerToolbar function. This function collects search data and doesn't consider case when $('select[multiple]').val() returns - empty array. Breaking change in jquery 3 described here - https://jquery.com/upgrade-guide/3.0/#breaking-change-select-multiple-with-nothing-selected-returns-an-empty-array

**Comment by tonytomov** [comment] 2019-02-06 03:35
Thanks.  Will check this.

**Comment by tonytomov** [comment] 2019-02-12 11:33
Hello,

First of all sorry for delay. I have checked this and it is rut. The fix is available in Github. Also fixed the dialogue search too.

Thank you for finding this problem.

If you think that the issue is fixed, please close it.

Best Regards,
Tony

**Comment by Koi7** [comment] 2019-02-12 12:44
Hi. I will check this when you release new version of jqGrid. I'm not going to build it by myself.

**Comment by tonytomov** [comment] 2019-11-14 09:06
Hope you tested it and is OK. I close it. In case you find something, please reopen the issue

**Closed by tonytomov** 2019-11-14 09:06 UTC
Labels: Bug
