### ISSUE TITLE
Toggle Multi Select

### ISSUE THREAD

**Issue by gewisser** [tonytomov/jqGrid#768] opened 2016-03-01 14:07 UTC
Hello.
How to switch the table in multiselect mode?
```javascript
$("#table").jqGrid('setGridParam',{ multiselect: true}).trigger("reloadGrid");
```
Does not work.

Example: http://sim-hosting.ru/test.html  (open in firefox)

**Comment by tonytomov** [comment] 2016-03-01 14:58
Hello,

Standard jqGrid does not support dynamically creation of columns and this enabling multiselect dynamically with setGridParam will not take effect.

In the web there are a lot of post regarding this with very heavy solutions which require a lot of code. Also you can search our public forum http://guriddo.net/?page_id=4

In this post I will show you how this can be done very elegant knowing all the grid options and how they work.

Initially jqGrid will be created with two options: multiselect and multiboxonly set to true. 
the first will guarantee the the multi selection is enabled and the second option will guarantee us that instead this will act as single select. With second options multiselect works only if the checkbox is clicked in all other cases it will act as single select.

The trick is to hide the multiselect column initially and later if you want to enable it you will need just to show it and eventually set the multiboxonly to false (which can be changed dynamically) bello is the code sniplet

```
$("#grid").jqGrid({
...
   multiselect: true,
   multiboxonly : true,
...
});
$("#grid").jqGrid('hideCol','cb');

// to enable dynamically pure  multiselect do

$("#grid").jqGrid('setGridParam',{multiboxonly : false});
$("#grid").jqGrid('showCol','cb');

// to disable dynamically do
$("#grid").jqGrid('setGridParam',{multiboxonly : true});
$("#grid").jqGrid('hideCol','cb');

```

Note that with this solution you do not need to reload the grid.
Enjoy

**Comment by gewisser** [comment] 2016-03-01 16:19
It works!
Thank you.

It would be great if you implement everything inside.
For example, add the option: 
```javascript
...
dynmultiselect: true,
...
```

and use it like so:
```javascript
$("#table").jqGrid('ToggleMultiSelect');
```
or 
```javascript 
$("#table").jqGrid('MultiSelect', true/false);
```

**Comment by tonytomov** [comment] 2016-03-02 13:06
Hello,

Thank you very much for the suggestion. I will consider this in the future releases.
Please, if you think that the problem is resolved consider closing the issue.

**Closed** 2016-03-02 14:59 UTC
Labels: Question
