### ISSUE TITLE
The column header  sorted icon disappear in jqgrid bootstrap 

### ISSUE THREAD

**Issue by pmsl987** [tonytomov/jqGrid#840] opened 2017-02-20 08:16 UTC
I delete the line of 890 in  **ui.jqgrid-bootstrap.css**,it is work.
This is bug?

**Comment by tonytomov** [comment] 2017-02-20 08:21
Hello,

Please, this is not a serious. Can you please let us know with example what you do and which exactly  line you have deleted? Which class? From which version?
You know that we have different version and 890 line does not correspond to your 890 line.

I hope you understand.

Kind Regards,
Tony

**Comment by pmsl987** [comment] 2017-02-20 10:12
I use **Guriddo_jqGrid_JS_5_2_X_demo**.
The site(http://www.guriddo.net/demo/bootstrap/) can disappear,but down demo can't disappear.

**Comment by tonytomov** [comment] 2017-02-20 10:15
Sorry,

I'm unable to understand what you mean.

Regards,

**Comment by tonytomov** [comment] 2017-02-22 14:51
I will close the issue. If you have problems, please reopen it

**Closed by tonytomov** 2017-02-22 14:51 UTC

**Comment by heyusysu** [comment] 2017-02-24 02:54
I find this bug too. In the demo website [http://www.guriddo.net/demo/bootstrap/](url), It can't reproduce because the css is not correct, there is a spelling mistake. The sorted icon will be hidden if you fix this css bug.

> .ui-jqgrid .ui-jqgrid-htable .ui-th-div {
    height: 17px;
    margin-top: 5px;
    display: inine-block; ==> spelling mistake
}

**Comment by tonytomov** [comment] 2017-02-24 08:27
Hello,

Thanks - that explain it. Thank you both. @pmsl987  sorry that I do not understand you correct.

The problem is fixed and the line

```css
display: inline-block;
```

is removed from the css
