### ISSUE TITLE
Cannot read property 'cellLayout' of undefined - jQuery 3.1.1

### ISSUE THREAD

**Issue by Legends** [tonytomov/jqGrid#839] opened 2017-02-15 17:18 UTC
When I change back to jQuery 2.1.1 the error is gone.

The error message:

> Uncaught TypeError: Cannot read property 'cellLayout' of undefined
>     at HTMLTableElement.<anonymous> (jquery.jqGrid.js:3397)
>     at Function.each (jquery-3.1.1.js:368)
>     at jQuery.fn.init.each (jquery-3.1.1.js:157)
>     at jQuery.fn.init.showHideCol (jquery.jqGrid.js:3396)
>     at jQuery.fn.init.$.fn.jqGrid (jquery.jqGrid.js:772)
>     at HTMLTableElement.<anonymous> (jquery.jqGrid.js:3442)
>     at Function.each (jquery-3.1.1.js:368)
>     at jQuery.fn.init.each (jquery-3.1.1.js:157)
>     at jQuery.fn.init.showCol (jquery.jqGrid.js:3442)
>     at jQuery.fn.init.$.fn.jqGrid (jquery.jqGrid.js:772)

The code:
```
			var jqgrid_data = [{
				id: "1",
				date: "2007-10-01",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "2",
				date: "2007-10-02",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "3",
				date: "2007-09-01",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}, {
				id: "4",
				date: "2007-10-04",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "5",
				date: "2007-10-05",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "6",
				date: "2007-09-06",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}, {
				id: "7",
				date: "2007-10-04",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "8",
				date: "2007-10-03",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "9",
				date: "2007-09-01",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}, {
				id: "10",
				date: "2007-10-01",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "11",
				date: "2007-10-02",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "12",
				date: "2007-09-01",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}, {
				id: "13",
				date: "2007-10-04",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "14",
				date: "2007-10-05",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "15",
				date: "2007-09-06",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}, {
				id: "16",
				date: "2007-10-04",
				name: "test",
				note: "note",
				amount: "200.00",
				tax: "10.00",
				total: "210.00"
			}, {
				id: "17",
				date: "2007-10-03",
				name: "test2",
				note: "note2",
				amount: "300.00",
				tax: "20.00",
				total: "320.00"
			}, {
				id: "18",
				date: "2007-09-01",
				name: "test3",
				note: "note3",
				amount: "400.00",
				tax: "30.00",
				total: "430.00"
			}];

			jQuery("#jqgrid").jqGrid({

				data: jqgrid_data,
				datatype: "local",
				height: 'auto',
				colNames: ['Actions', 'Inv No', 'Date', 'Client', 'Amount', 'Tax', 'Total', 'Notes'],
				colModel: [{
					name: 'act',
					index: 'act',
					sortable: false
				}, {
					name: 'id',
					index: 'id'
				}, {
					name: 'date',
					index: 'date',
					editable: true
				}, {
					name: 'name',
					index: 'name',
					editable: true
				}, {
					name: 'amount',
					index: 'amount',
					align: "right",
					editable: true
				}, {
					name: 'tax',
					index: 'tax',
					align: "right",
					editable: true
				}, {
					name: 'total',
					index: 'total',
					align: "right",
					editable: true
				}, {
					name: 'note',
					index: 'note',
					sortable: false,
					editable: true
				}],
				rowNum: 10,
				rowList: [10, 20, 30],
				pager: '#pjqgrid',
				sortname: 'id',
				toolbarfilter: true,
				viewrecords: true,
				sortorder: "asc",
				gridComplete: function () {

					var ids = jQuery("#jqgrid").jqGrid('getDataIDs');
					for (var i = 0; i < ids.length; i++) {
						var cl = ids[i];
						be = "<button class='btn btn-xs btn-default' data-original-title='Edit Row' onclick=\"jQuery('#jqgrid').editRow('" + cl + "');\"><i class='fa fa-pencil'></i></button>";
						se = "<button class='btn btn-xs btn-default' data-original-title='Save Row' onclick=\"jQuery('#jqgrid').saveRow('" + cl + "');\"><i class='fa fa-save'></i></button>";
						ca = "<button class='btn btn-xs btn-default' data-original-title='Cancel' onclick=\"jQuery('#jqgrid').restoreRow('" + cl + "');\"><i class='fa fa-times'></i></button>";
						//ce = "<button class='btn btn-xs btn-default' onclick=\"jQuery('#jqgrid').restoreRow('"+cl+"');\"><i class='fa fa-times'></i></button>";
						//jQuery("#jqgrid").jqGrid('setRowData',ids[i],{act:be+se+ce});
						jQuery("#jqgrid").jqGrid('setRowData', ids[i], {
							act: be + se + ca
						});
					}
					iscmenabled = false; // is not enabled after sort/load
					wrapButtons();
					doresponsive();
				},
				//onRightClickRow: function (rowid, iRow, iCol, e) {
				//	alert(rowid + iRow + iCol + e);
				//	e.preventDefault();

				//},
				editurl: "dummy.html",
				caption: "SmartAdmin jQgrid Skin",
				multiselect: true,
				autowidth: true,

			});

			// footer left toolbar refresh/search/delete
			jQuery("#jqgrid").jqGrid('navGrid', "#pjqgrid", {
				edit: false,
				add: false,
				del: true
			});
			// edit/save/cancel
			jQuery("#jqgrid").jqGrid('inlineNav', "#pjqgrid");
```

**Comment by tonytomov** [comment] 2017-02-16 09:39
Hello,

I can't reproduce the problem with your code using jQuery 3.1.1. The code run a functions in gridComplete - wrapButtons(); and doresponsive(); which are not posted in your code.

Can you please describe what you do (a order for a actions) so that this error is raised?
Thank you

Kind Regards,
Tony

**Comment by tonytomov** [comment] 2017-02-22 14:53
Since I do not have response for this problem I will close the issue. Please feel free to reopen it if you have problems.

**Closed by tonytomov** 2017-02-22 14:53 UTC
