### ISSUE TITLE
Problem with the width of the grid

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#779] opened 2016-04-13 08:22 UTC
Hello again :),
It seems that there is another bug with the computed size of the grid.
As you can see in the following screenshot of my jqgrid, the text and the searching box in the last column of the grid are going out of the border. 
![1](https://cloud.githubusercontent.com/assets/18188368/14487505/99bc0690-016b-11e6-81bd-47ced7d48837.JPG)
 

This happens in any grid and at any time the grid is computed (e.g. resizing the window of the browser).

I noticed that for some reason the grid is 2 pixels lesser than it should be.
Inspecting the appropriate div of the grid and adding 2 pixels in the style fixes this problem as you can see in the next screenshot.

![2](https://cloud.githubusercontent.com/assets/18188368/14487509/9dd58ea4-016b-11e6-9c7e-8070c0a59b00.JPG)

Thanks

**Comment by tonytomov** [comment] 2016-04-13 18:43
Hello,

Thank you for the bug report. 
Can you please explain where and on which div you have added 2px?
How you add these pixels?

Kind Regards

**Comment by yannniskargakis** [comment] 2016-04-14 08:20
Hello,
I inspect the html code using a browser addon.
This was a temporary solution just to detect the problem.
Specifically I changed the line:

`<div class="ui-jqgrid " id="gbox_myGrid" dir="ltr" style="width: 1116px;">`

to:

`<div class="ui-jqgrid " id="gbox_myGrid" dir="ltr" style="width: 1118px;">`

Note that this happens in any computed width of jqgrid (adding 2 more pixels fixes the problem).

**Comment by tonytomov** [comment] 2016-04-15 00:34
Hello,

Thank you for explanation.
It is important to note that this happen only when using Bootstrap.
We will try to reproduce the problem and let you know. 

If you can provide us a demo showing the problem, this will be very good.
I ask about this, because I can't see the problem in our Bootstrap demos.

Kind Regards

**Comment by yannniskargakis** [comment] 2016-04-15 09:19
[Here](https://github.com/tonytomov/jqGrid/files/220631/index.txt) is one of your own bootsrap examples that i have modified to cause the problem.

A screenshot too:
![capture](https://cloud.githubusercontent.com/assets/18188368/14557099/379dade8-0304-11e6-89b1-60b17434c3fe.JPG)

**Comment by tonytomov** [comment] 2016-04-18 15:23
Thanks.

I was able to reproduce the problem. Will replay when a solution is available.

Kind Regards.

**Comment by tonytomov** [comment] 2016-04-19 10:02
Hello,

I have fixed the problem https://github.com/tonytomov/jqGrid/issues/779 . Could you please confirm if it is ok for you and if yes close the issue.

Thank you.

Kind Regards,
Tony

**Comment by yannniskargakis** [comment] 2016-04-20 07:04
Hello,
The problem has been fixed only for the contents of the grid, but not for the top pager. The text in the top pager (specifically in div ui-jqgrid-hdiv) still is going out of the border. See my previous example and the following screenshot
![capture](https://cloud.githubusercontent.com/assets/18188368/14665917/1c34786e-06df-11e6-97a3-721e64f627f2.JPG)

**Comment by tonytomov** [comment] 2016-04-20 12:29
Hello,

I have fixed the problem for the other grid elemetns.
Please let me know if it fine for you.

To be a honest I do not like this fix, since when working with jQueryUI theming it is ok.
The problem is more generic and is connected with Bottstrap theming.
Will try to investigate the problem later.

Kind Regards,
Tony

**Comment by yannniskargakis** [comment] 2016-04-21 08:48
Hello,
Thanks for your fix. For now it is ok.
If you have a more official solution please inform me.

**Comment by tonytomov** [comment] 2016-04-25 07:43
Hello,

I will close the issue. If I found another solution I will let you knowASAP.

Kind Regards,
Tony

**Closed by tonytomov** 2016-04-25 07:43 UTC
Labels: Bug

**Comment by yannniskargakis** [comment] 2017-08-02 09:53
Hello,
The same bug occurs updating to 5.2.1.
Could you fix it please?
Thanks

**Comment by tonytomov** [comment] 2017-08-02 15:41
Hello,

Can you please get the latest build from gitHub and test. Here is the fix: https://github.com/tonytomov/jqGrid/commit/8841e8d917785575059ddbdab9ce2fd9b1e0eea0

**Comment by yannniskargakis** [comment] 2017-08-03 11:50
Hi,
The problem still exists in the latest build. You can confirm it using my old example above.
I noticed that if you resize the window the grid takes the right size, but it lose it reloading the page.

**Comment by tonytomov** [comment] 2017-08-03 12:02
With which StyleUI is this?

**Comment by yannniskargakis** [comment] 2017-08-03 12:06
Bootrap UI

**Comment by tonytomov** [comment] 2017-08-03 12:11
OS and browser?

**Comment by yannniskargakis** [comment] 2017-08-03 12:14
Windows 7 - both Chrome 60 and Firefox 54

**Comment by tonytomov** [comment] 2017-08-03 13:14
The problem is somewhere in the altRows setting. If you disable it it is OK. Will check it, but it seems it is a bootstrap problem

**Comment by tonytomov** [comment] 2017-08-03 14:50
Could you please try it. I have done some missed thing when recalculating the scrollOffset for bootstrap

**Comment by yannniskargakis** [comment] 2017-08-04 09:22
Now it works as expected.
Thanks for your fix :)
