### ISSUE TITLE
"progressBar" dosen't work in chrome and ie, just firefox

### ISSUE THREAD

**Issue by chapsticks** [tonytomov/jqGrid#759] opened 2016-01-25 09:00 UTC
when i edit data in "inline mode",  then i click save button, the "progressBar" dosen't work, but work in firefox, is this a bug?

**Comment by tonytomov** [comment] 2016-01-25 09:16
Hello,

It depend. If you save data locally it wont appear since the operations quick.
In case of server side saving data - it depend too. 

The real test is if you can delay the server response when the data is saving.

To see the problem a  test case will be highly appreciated.

Regards

**Comment by chapsticks** [comment] 2016-01-25 09:26
Thanks for your reply:

I save data on server side , and,  i had delay the server response. So, i am very confused

**Comment by tonytomov** [comment] 2016-01-25 09:27
Does the problem appear or the dialog show.
If the problem persist - which version you use?

**Comment by chapsticks** [comment] 2016-01-25 10:03
the gif image is my test, p

lease have a look
in firefox, there is a black layer
in chrome , there is nothing,
version is 4.6.0 and 5.0.2

image upload faild,please visit this url      http://pan.baidu.com/s/1c1oDRDe

thanks a lot

**Comment by chapsticks** [comment] 2016-01-25 10:05
sorry ,this url is not need download,
http://7xool8.com1.z0.glb.clouddn.com/test.gif

**Comment by tonytomov** [comment] 2016-01-26 10:32
Hello,

I just tested this and it work fine for me. I can not reproduce the problem.
To see the problem I need a working test case and not pictures.

Regards,
Tony

**Comment by tonytomov** [comment] 2016-07-28 09:40
Hello,

I will close the issue. Please consider reopen if the problem exists for you and you have test case demo starting it

**Closed by tonytomov** 2016-07-28 09:40 UTC
Labels: Problem
