### ISSUE TITLE
After loading state of the toolbar button is gone

### ISSUE THREAD

**Issue by gewisser** [tonytomov/jqGrid#726] opened 2015-09-13 19:12 UTC
See video
https://www.youtube.com/watch?v=34HTPb_XY68

**Comment by gewisser** [comment] 2015-09-14 08:56
Another video:
https://www.youtube.com/watch?v=Evp00BQWwUE

**Comment by tonytomov** [comment] 2015-09-14 09:12
Hello,

Thanks for posting this.
We know about this problem  and it is fixed in the gitHub.
see related fix here: https://github.com/tonytomov/jqGrid/commit/8102e0f78c8e291b4f452fb718d45d68800961e9

The update will be available soon with the upcomming bug fix release.

Kind Regards

**Comment by gewisser** [comment] 2015-09-14 10:12
Thank you, but the problem is shown in the video release on "jquery.jqGrid" - 2015-08-18 (8102e0f) played.

**Comment by tonytomov** [comment] 2015-09-14 10:27
I this case I need a test case with a description of reproducing the error.
Thank you

**Comment by gewisser** [comment] 2015-09-14 11:56
Please
http://sim-hosting.ru/test.html

**Comment by tonytomov** [comment] 2015-09-14 12:14
Hello,

You have missed to set storeNavOptions in navigarot - navGrid.
Do this and the buttons will be restored.
```
LogGrid.navGrid('#ServicePager_log', { storeNavOptions : true, edit: false, add: false, del: false, search: true, refresh: true, view: false, position: "left", cloneToTop: true });
```

**Comment by gewisser** [comment] 2015-09-14 12:38
I updated the "test.html". Problem still exists.

**Comment by tonytomov** [comment] 2015-09-14 12:42
Sorry,

This is a grid option and not navigator one. Please set this in main grid options
```
...jqGrid ({
...
storeNavOptions : true
...
});
```

**Comment by gewisser** [comment] 2015-09-14 13:03
Working!

Parse Video # 2

The same test page http://sim-hosting.ru/test.html
Execute all the steps.

Target: to add buttons after the restoration of the state.

**Comment by tonytomov** [comment] 2015-09-14 13:34
Thanks,

I have try to fix the problem: https://github.com/tonytomov/jqGrid/commit/f3741deeb0cd518fcbe3bd1c04df085e66ffe0a2

**Comment by gewisser** [comment] 2015-09-14 13:55
Good. Almost corrected.

How about a "TypeError: this [0] .p is undefined", if you do step 4?

**Comment by tonytomov** [comment] 2015-09-14 14:16
Since we use destroyGrid - which acts as deep delete, your reference to the grid is lost .
In order this to work you will need to

$("#table_log").jqGrid('navGrid'...);

instead of

LogGrid.jqGrid('navGrid',...);

on button click when you try to add a custom button

**Comment by gewisser** [comment] 2015-09-14 14:22
Thank you. Everything is working.

**Comment by tonytomov** [comment] 2015-09-14 14:27
Ok. I will close the issue. 
Thanks.

**Closed by tonytomov** 2015-09-14 14:27 UTC
Labels: Bug

**Comment by gewisser** [comment] 2015-09-14 15:08
Hurry up. With the upgrade f3741de first problem came with the disappearance of the buttons after loading. Steps 1 -> 3
http://sim-hosting.ru/test.html

**Comment by tonytomov** [comment] 2015-09-14 15:28
Thanks again.
Try with this fix: https://github.com/tonytomov/jqGrid/commit/b82351cedd3fb81eb69f88e629c306f7360a0679

**Comment by gewisser** [comment] 2015-09-14 15:34
Everything is working.

Thank you.

**Comment by gewisser** [comment] 2015-09-15 14:34
Where else something is wrong.

For myself, I decided to still not save button the bottom panel and load them always after loading the configuration grid.

storeNavOptions: false

After loading grid state from local storage, the buttons at the bottom are not loaded.
Maybe I'm doing something wrong.

http://sim-hosting.ru/test.html

**Comment by tonytomov** [comment] 2015-09-16 07:57
The necessary and sufficient condition to store and load  navigaror buttons is to set 

storeNavOptions to true.
In your demo in step 2 before to add the navigator and buttons you will need to setGridParam storeNavOptions.

More over you have two button element with the same id and your button in step 5 never lunch (check it).
Please check your code for errors before to post a demo.

Thank you.

Kind Regards

**Comment by gewisser** [comment] 2015-09-16 09:06
Thank you.
2 buttons with an identical id fixed.

The situation is this. If I turn on the option storeNavOptions, it is stored in the same code:

```javascript
{
	buttonicon: "ui-icon-calculator",
	title: "Настройка колонок",
	caption: "Столбцы",
	position: "last",
	onClickButton: function () {
		// call the column chooser method
		$("#table_log").jqGrid('columnChooser');
	}
}
```

onClickButton code will change, and it should not be stored in the repository, or will always recover the old version ...

**Comment by tonytomov** [comment] 2015-09-16 09:32
I'm little confused understanding what you want to achieve!

**Comment by gewisser** [comment] 2015-09-16 10:06
The goal is simple:

1. Initialize jqGrid with buttons at the bottom (loadBtn ();)
The user's personal cabinet changes the size of the columns, their position, their presence, and save these settings.
(Step - 1, Step - 2)


2. The next time you open the page the user automatically loaded grid settings (Step 4)

3. Automatically initialize navGrid navButton loaded from the repository to the grid by running (loadBtn ()); (Step 5)

In Step - 5 buttons are not initialized to restore the grid from the repository

Save navButton not necessary, otherwise restored handler code pressing the buttons, buyout can be changed in the future.

**Comment by tonytomov** [comment] 2015-09-16 12:13
Then what is the problem to use storeNavOptions:true. If this is true and you call loadBtn, then after restoring the state you should not again call loadBtn, since it is already called in the 1.step.

**Comment by gewisser** [comment] 2015-09-16 15:09
If storeNavOptions: true is stored in the repository this:


```javascript
...
[

    "#ServicePager_log",

    {
        "caption": "Столбцы",
        "title": "Настройка колонок",
        "buttonicon": "ui-icon-calculator",
        "onClickButton": "function () {$("#table_log").jqGrid('columnChooser');",
        "position": "last",
        "cursor": "pointer",
        "internal": false
    }

]
...
```

If I change the code in the future
```javascript
...

 $("#table_log").navButtonAdd('#ServicePager_log',
                        {
                            buttonicon: "ui-icon-calculator",
                            title: "Настройка колонок",
                            caption: "Столбцы",
                            position: "last",
                            onClickButton: function () {
								alert('hello 2 change');
                            }
                        }
                );

...
```

the user will see the text "hello 2 change" when you press the button after restoring the navButton settings?
