### ISSUE TITLE
GridUnload missing from 4.8?

### ISSUE THREAD

**Issue by dizzy0ny** [tonytomov/jqGrid#696] opened 2015-03-22 00:40 UTC
Getting 'no such method defined' with the latest, but if i go back to an older version, it works fine (i tried 4.7).

$("#gridCot").jqGrid('GridUnload');

**Comment by tonytomov** [comment] 2015-03-22 07:27
Hello,

The method was chaged. Please read the upgarde notes from the official release download or read them here: http://guriddo.net/?p=123585

Kind Regards

**Comment by dizzy0ny** [comment] 2015-03-23 07:12
Thanks, if i may suggest...in your release notes, have a section labeled "Breaking Changes". Often times when deciding to upgrade, that is what most users will want to know.

**Comment by tonytomov** [comment] 2015-03-23 11:38
Hello,

Thanks for the suggestion. This will be added definitley

**Comment by tonytomov** [comment] 2015-03-23 13:32
Can you please confirm if the problem is fixed, so that I close the issue.
Thank you

**Comment by dizzy0ny** [comment] 2015-03-23 15:06
Yes it is, thank you!  using the v4.8 api as described in the release notes works.
  
$.jgrid.gridUnload("#grid")

**Closed** 2015-03-23 15:26 UTC
