### ISSUE TITLE
Elements of top pager are not aligned to the center

### ISSUE THREAD

**Issue by yannniskargakis** [tonytomov/jqGrid#776] opened 2016-03-31 11:09 UTC
Hello, 

It seems that there is a problem in the css style of the top pager.
Specifically if I add a top pager in the grid (toppager: true, cloneToTop: true) the elements of the top pager (the number of page, views etc) are aligned to the left,  while in the bottom pager are in the center. It would be better to have a uniformity of pagers.
 
[Here](https://github.com/tonytomov/jqGrid/files/197461/index.txt) is one of your own examples (jqgridjs\edit_add_delete\dialogs) that I modified to add a top pager.

PS: I am using the latest release of jqgrid 5.1.0

Thank you

**Comment by tonytomov** [comment] 2016-04-01 08:31
Hello,

Thanks for reporting the bug. We have fixed the problem. Please let us know if it is working for you and close the issue in case it is ok.

Thank you.
Kind Regards,
Tony

**Comment by yannniskargakis** [comment] 2016-04-04 06:42
Bug has been fixed.
Thanks.

**Comment by nelson6340** [comment] 2016-07-14 20:25
Hello, please tell me where I find the updated library with the bug fixed, please share me the url to it. thank you very much.

**Comment by tonytomov** [comment] 2016-07-15 13:45
Hello,

This is the link to the latest build: https://github.com/tonytomov/jqGrid/archive/master.zip

Kind Regards

**Comment by tonytomov** [comment] 2016-07-28 09:36
Suppose the problem is fixed and I will close the issue. Please reopen if there is a problem

**Closed by tonytomov** 2016-07-28 09:36 UTC

**Comment by yannniskargakis** [comment] 2016-07-28 18:23
What about #801?
