### ISSUE TITLE
Two editable cell will be selected after expand a subgrid!

### ISSUE THREAD

**Issue by kodyli** [tonytomov/jqGrid#856] opened 2017-05-09 21:56 UTC
The problem occurs when using an editable grid with a subgrid. You can reproduce the case by following the steps listed below:
1. Select an editable cell in the second row.
![image](https://cloud.githubusercontent.com/assets/15198354/25873370/2063346c-34c3-11e7-8105-72117905026d.png)
2. Keep the cursor in the editable cell(**important!!!**), and then click the expand icon to open a subgrid of the first row in parent grid.
![image](https://cloud.githubusercontent.com/assets/15198354/25873413/4b9e32c6-34c3-11e7-8be2-19a91f9f37a0.png)
3. Click the editable cell in the first row. You will get an error dialog. 
![image](https://cloud.githubusercontent.com/assets/15198354/25873708/5e3e4334-34c4-11e7-914e-054f84efdcda.png)
4. After close the dialog, the two editable cells are both selected.
![image](https://cloud.githubusercontent.com/assets/15198354/25873842/d8ffb7e2-34c4-11e7-9d71-82607b784d81.png)
![image](https://cloud.githubusercontent.com/assets/15198354/25873864/e8545a04-34c4-11e7-9d16-53b778a2f868.png)
![image](https://cloud.githubusercontent.com/assets/15198354/25873976/5d5b9e84-34c5-11e7-9ab2-25cd3572c591.png)

When I debug it. it seems the  row indexes still the same after the expand.

The attached is the test case. please have a look. 
[index.zip](https://github.com/tonytomov/jqGrid/files/988110/index.zip)

**Comment by tonytomov** [comment] 2017-05-12 10:02
Hello,

I have fixed the problem with this commit: https://github.com/tonytomov/jqGrid/commit/2b709962783c2707ff2cc39c7741489412e3acf4 
Note that we need to make more fixes, but for now it is working.

Please let us know if the problem is fixed.

Best Regards,
Tony

**Comment by kodyli** [comment] 2017-05-12 15:27
Thanks.

**Comment by tonytomov** [comment] 2017-12-13 14:54
I will close the issue

**Closed by tonytomov** 2017-12-13 14:54 UTC
Labels: Bug
